### ISSUE TITLE
Transmitting packets without being connected to a network

### ISSUE THREAD

**Issue by justinklchan** [SodaqMoja/Sodaq_nbIOT#2]
I am living in the United States, where I am aware there is no NB-IoT coverage. I would like to capture NB-IoT packets that are transmitted from this shield as part of a research project. 

I am using the NB-IoT Shield DeLuxe (N201, Band 5).

Is there a way I can do that with the current shield or is that not possible? Do I need a SIM card or is there some workaround where I can get the shield to just send arbitrary packets. 

I want to note that I intend to transmit the packets along a wire and capture them using a software defined radio. I will not be transmitting them over the air, so there is no legal issue of transmitting on a non-ISM band.

**Comment by SodaqMoja** [comment]
Would you mind to post this question on our forum? There are (hopefully) more people that can jump in.
At http://forum.sodaq.com/

**Comment by justinklchan** [comment]
I already did that, but it looks like my account is on hold, and my post is waiting approval. Can you approve my account and my post?

**Comment by justinklchan** [comment]
Ok I posted it here:
http://forum.sodaq.com/t/transmitting-packets-without-being-connected-to-a-network/1251

**Comment by justinklchan** [comment]
Long story short this cannot be done. If anyone wants to accomplish this use the LTE package in Matlab 2017b onwards. Refer to this link:
https://www.mathworks.com/examples/lte-system/mw/lte_product-NPDSCHBlockErrorRateExample-nb-iot-npdsch-block-error-rate-simulation-and-waveform-generation

Their example file is pretty good and you can modify the data and modulation schemes, and the file will give you the complex IQ valued signal which can you transmit using a software defined radio.
